Uni\AdminBundle\Entity\ProductSubcategory:
    type: entity
    table: ProductSubcategory
    repositoryClass: Uni\AdminBundle\Entity\ProductSubcategoryRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    manyToOne:
        user:
            targetEntity: Uni\AdminBundle\Entity\User
            inversedBy: products
        category:
            targetEntity: Uni\AdminBundle\Entity\ProductCategory
            inversedBy: subcategories
            joinColumn:
                onDelete: Cascade
    oneToMany:
        products:
            targetEntity: Uni\AdminBundle\Entity\Product
            mappedBy: subcategory
    fields:
        name:
            type: string
            length: 100
            nullable: true
        slug:
            type: string
            length: 100
            nullable: true
        createdAt:
            type: datetime
            gedmo:
                timestampable:
                    on: create
        updatedAt:
            type: datetime
            gedmo:
                timestampable:
                    on: update
        deleted_at:
            type: datetime
            nullable: true
    gedmo:
        soft_deleteable:
            field_name: deleted_at
            time_aware: false
    lifecycleCallbacks: {  }
