Uni\AdminBundle\Entity\Product:
    type: entity
    table: Product
    repositoryClass: Uni\AdminBundle\Entity\ProductRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    manyToOne:
        user:
            targetEntity: Uni\AdminBundle\Entity\User
            inversedBy: products
    fields:
        title:
            type: string
            length: 100
            nullable: true
        content:
            type: text
            nullable: true
        image:
            type: string
            length: 200
            nullable: true
        created_at:
            type: datetime
            gedmo:
                timestampable:
                    on: create
        updated_at:
            type: datetime
            gedmo:
                timestampable:
                    on: update
        deleted_at:
            type: datetime
            nullable: true
    gedmo:
        soft_deleteable:
            field_name: deleted_at
            time_aware: false
    lifecycleCallbacks: {  }
