Uni\AdminBundle\Entity\SocialMediaAvailable:
    type: entity
    table: SocialMediaAvailable
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 100
        icon:
            type: string
            length: 100
        hexcolor:
            type: string
            length: 10
