Unisystem\AdminBundle\Entity\Subcategory:
    type: entity
    table: Subcategory
    repositoryClass: Uni\AdminBundle\Entity\SubcategoryRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    manyToOne:
        category:
            targetEntity: Uni\AdminBundle\Entity\Category
            inversedBy: subcategories
            joinColumn:
                onDelete: SET NULL
    oneToMany:
        products:
            targetEntity: Uni\AdminBundle\Entity\Product
            mappedBy: subcategory
    fields:
        name:
            type: string
            length: 300
            nullable: true
        slug:
            type: string
            length: 300
            nullable: true
        createdAt:
            type: datetime
            gedmo:
                timestampable:
                    on: create
        updatedAt:
            type: datetime
            gedmo:
                timestampable:
                    on: update
    lifecycleCallbacks: {  }
