Uni\AdminBundle\Entity\User:
    type: entity
    table: User
    repositoryClass: Uni\AdminBundle\Entity\UserRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    oneToMany:
        features:
            targetEntity: Uni\AdminBundle\Entity\Feature
            mappedBy: user
        photographies:
            targetEntity: Uni\AdminBundle\Entity\Photography
            mappedBy: user
    fields:
        brand:
            type: string
            length: 100
            nullable: true
        name:
            type: string
            length: 100
            nullable: true
        domain:
            type: string
            length: 100
            nullable: true
        brand_primary_color:
            type: string
            length: 100
            nullable: true
        brand_secondary_color:
            type: string
            length: 100
            nullable: true

        clientname:
            type: string
            length: 100
            nullable: true
        clientphone:
            type: string
            length: 20
            nullable: true
        clientemail:
            type: string
            length: 100
            nullable: true
        clientaddress:
            type: string
            length: 100
            nullable: true

        maintitle:
            type: string
            length: 20
            nullable: true
        mainsubtitle:
            type: string
            length: 100
            nullable: true
        maincalltoaction:
            type: string
            length: 20
            nullable: true

        abouttitle:
            type: string
            length: 20
            nullable: true
        aboutcontent:
            type: text
            nullable: true

        featuretitle:
            type: string
            length: 20
            nullable: true
        featurecontent:
            type: text
            nullable: true

        contacttitle:
            type: string
            length: 20
            nullable: true
        contactcontent:
            type: text
            nullable: true
        contactphone:
            type: string
            length: 20
            nullable: true
        contactemail:
            type: string
            length: 100
            nullable: true
        contactaddress:
            type: string
            length: 100
            nullable: true

        created_at:
            type: datetime
            gedmo:
                timestampable:
                    on: create
        updated_at:
            type: datetime
            gedmo:
                timestampable:
                    on: update
        deleted_at:
            type: datetime
            nullable: true
    gedmo:
        soft_deleteable:
            field_name: deleted_at
            time_aware: false
    lifecycleCallbacks: {  }
