liip_imagine:
    resolvers:
        default:
            web_path: ~
    filter_sets:
        cache: ~
        main_photography:
            quality: 75
            filters:
                upscale: { min: [1920, 1080] }
                thumbnail: { size: [1366, 900], mode: outbound }
        main_photography_small:
            quality: 75
            filters:
                upscale: { min: [160, 120] }
                thumbnail: { size: [160, 120], mode: outbound }
        feature_photography_large:
            quality: 75
            filters:
                upscale: { min: [1366, 768] }
                thumbnail: { size: [1366, 768], mode: outbound }
        feature_photography:
            quality: 75
            filters:
                upscale: { min: [800, 600] }
                thumbnail: { size: [800, 600], mode: outbound }
        feature_photography_small:
            quality: 75
            filters:
                upscale: { min: [160, 120] }
                thumbnail: { size: [160, 120], mode: outbound }
        product_photography_large:
            quality: 75
            filters:
                upscale: { min: [900, 900] }
                thumbnail: { size: [900, 900], mode: outbound }
        product_photography:
            quality: 75
            filters:
                upscale: { min: [600, 600] }
                thumbnail: { size: [600, 600], mode: outbound }
        product_photography_small:
            quality: 75
            filters:
                upscale: { min: [120, 120] }
                thumbnail: { size: [120, 120], mode: outbound }
