liip_imagine:
    resolvers:
        default:
            web_path: ~
    filter_sets:
        cache: ~
        main_photography:
            quality: 75
            filters:
                upscale: { min: [1920, 1080] }
                thumbnail: { size: [1366, 900], mode: outbound }
        feature_photography:
            quality: 75
            filters:
                upscale: { min: [800, 600] }
                thumbnail: { size: [800, 600], mode: outbound }
