uni_catalog:
    resource: "@UniCatalogBundle/Resources/config/routing.yml"
    prefix:   /

uni_control_panel:
    resource: "@UniControlPanelBundle/Resources/config/routing.yml"
    prefix:   /controlpanel

#kore_user:
#    resource: "@UniUserBundle/Resources/config/routing.yml"
#    prefix:   /
#
#kore_agent:
#    resource: "@UniAgentBundle/Resources/config/routing.yml"
#    prefix:   /agent
#

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

uni_admin:
    resource: "@UniAdminBundle/Resources/config/routing.yml"
    prefix:   /admin

uni_page:
    resource: "@UniPageBundle/Resources/config/routing.yml"
    prefix:   /

_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"
