vich_uploader:
    db_driver: orm # or mongodb or propel or phpcr
    default_filename_attribute_suffix:  _name
    storage: file_system
    twig: true
    metadata:
        cache: file
        file_cache:
            dir: '%kernel.cache_dir%/vich_uploader'
        auto_detection: true
    mappings:
        main_photography:
            uri_prefix: uploads/mainphotography
            upload_destination: %kernel.root_dir%/../web/uploads/mainphotography
            namer: vich_uploader.namer_origname
        feature_photography:
            uri_prefix: uploads/feature
            upload_destination: %kernel.root_dir%/../web/uploads/feature
            namer: vich_uploader.namer_origname
