controlpanel_feature_index:
    path:     /
    defaults: { _controller: "UniControlPanelBundle:Feature:index" }
    methods:  GET

controlpanel_feature_show:
    path:     /{id}/show
    defaults: { _controller: "UniControlPanelBundle:Feature:show" }
    methods:  GET

controlpanel_feature_new:
    path:     /new
    defaults: { _controller: "UniControlPanelBundle:Feature:new" }
    methods:  [GET, POST]

controlpanel_feature_edit:
    path:     /{id}/edit
    defaults: { _controller: "UniControlPanelBundle:Feature:edit" }
    methods:  [GET, POST]

controlpanel_feature_delete:
    path:     /{id}/delete
    defaults: { _controller: "UniControlPanelBundle:Feature:delete" }
    methods:  DELETE
