controlpanel_photography_index:
    path:     /
    defaults: { _controller: "UniControlPanelBundle:Photography:index" }
    methods:  GET

controlpanel_photography_new:
    path:     /new
    defaults: { _controller: "UniControlPanelBundle:Photography:new" }
    methods:  [GET, POST]

controlpanel_photography_edit:
    path:     /{id}/edit
    defaults: { _controller: "UniControlPanelBundle:Photography:edit" }
    methods:  [GET, POST]

controlpanel_photography_delete:
    path:     /{id}/delete
    defaults: { _controller: "UniControlPanelBundle:Photography:delete" }
    methods:  DELETE
