controlpanel_product_index:
    path:     /
    defaults: { _controller: "UniControlPanelBundle:Product:index" }
    methods:  GET

controlpanel_product_show:
    path:     /{id}/show
    defaults: { _controller: "UniControlPanelBundle:Product:show" }
    methods:  GET

controlpanel_product_new:
    path:     /new
    defaults: { _controller: "UniControlPanelBundle:Product:new" }
    methods:  [GET, POST]

controlpanel_product_edit:
    path:     /{id}/edit
    defaults: { _controller: "UniControlPanelBundle:Product:edit" }
    methods:  [GET, POST]

controlpanel_product_delete:
    path:     /{id}/delete
    defaults: { _controller: "UniControlPanelBundle:Product:delete" }
    methods:  DELETE
