uni_admin_user:
    resource: "@UniAdminBundle/Resources/config/routing/user.yml"
    prefix:   /user

uni_admin_feature:
    resource: "@UniAdminBundle/Resources/config/routing/feature.yml"
    prefix:   /feature

uni_admin_photography:
    resource: "@UniAdminBundle/Resources/config/routing/photography.yml"
    prefix:   /photography

uni_admin_product:
    resource: "@UniAdminBundle/Resources/config/routing/product.yml"
    prefix:   /product