agent_item_index:
    path:     /
    defaults: { _controller: "UniAgentBundle:Item:index" }
    methods:  GET

agent_item_show:
    path:     /{id}/show
    defaults: { _controller: "UniAgentBundle:Item:show" }
    methods:  GET

agent_item_new:
    path:     /new
    defaults: { _controller: "UniAgentBundle:Item:new" }
    methods:  [GET, POST]

agent_item_edit:
    path:     /{id}/edit
    defaults: { _controller: "UniAgentBundle:Item:edit" }
    methods:  [GET, POST]

agent_item_delete:
    path:     /{id}/delete
    defaults: { _controller: "UniAgentBundle:Item:delete" }
    methods:  DELETE
