agent_product_index:
    path:     /
    defaults: { _controller: "UniAgentBundle:Product:index" }
    methods:  GET

agent_product_show:
    path:     /{id}/show
    defaults: { _controller: "UniAgentBundle:Product:show" }
    methods:  GET

agent_product_new:
    path:     /new
    defaults: { _controller: "UniAgentBundle:Product:new" }
    methods:  [GET, POST]

agent_product_edit:
    path:     /{id}/edit
    defaults: { _controller: "UniAgentBundle:Product:edit" }
    methods:  [GET, POST]

agent_product_delete:
    path:     /{id}/delete
    defaults: { _controller: "UniAgentBundle:Product:delete" }
    methods:  DELETE

agent_product_search_cm:
    path:     /searchcm
    defaults: { _controller: "UniAgentBundle:Product:searchcm" }
    methods:  GET
