<?php

namespace Uni\AdminBundle\Entity;

/**
 * PhotographyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PhotographyRepository extends \Doctrine\ORM\EntityRepository
{
}
