<?php

namespace Uni\AdminBundle\Entity;

/**
 * SocialMediaEnabledRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SocialMediaEnabledRepository extends \Doctrine\ORM\EntityRepository
{
}
