uni_control_panel_socialmediaenabled:
    resource: "@UniControlPanelBundle/Resources/config/routing/socialmediaenabled.yml"
    prefix:   /socialmediaenabled

uni_control_panel_feature:
    resource: "@UniControlPanelBundle/Resources/config/routing/feature.yml"
    prefix:   /feature

uni_control_panel_photography:
    resource: "@UniControlPanelBundle/Resources/config/routing/photography.yml"
    prefix:   /photography

uni_control_panel_account:
    resource: "@UniControlPanelBundle/Resources/config/routing/account.yml"
    prefix:   /account

uni_control_panel_product:
    resource: "@UniControlPanelBundle/Resources/config/routing/product.yml"
    prefix:   /product