uni_page_index:
    path: /
    defaults: { _controller: UniPageBundle:Page:index }

uni_page_feature:
    resource: "@UniPageBundle/Resources/config/routing/feature.yml"
    prefix:   /panel/feature
