admin_productsubcategory_index:
    path:     /
    defaults: { _controller: "UniAdminBundle:ProductSubcategory:index" }
    methods:  GET

admin_productsubcategory_show:
    path:     /{id}/show
    defaults: { _controller: "UniAdminBundle:ProductSubcategory:show" }
    methods:  GET

admin_productsubcategory_new:
    path:     /new
    defaults: { _controller: "UniAdminBundle:ProductSubcategory:new" }
    methods:  [GET, POST]

admin_productsubcategory_edit:
    path:     /{id}/edit
    defaults: { _controller: "UniAdminBundle:ProductSubcategory:edit" }
    methods:  [GET, POST]

admin_productsubcategory_delete:
    path:     /{id}/delete
    defaults: { _controller: "UniAdminBundle:ProductSubcategory:delete" }
    methods:  DELETE
