admin_productcategory_index:
    path:     /
    defaults: { _controller: "UniAdminBundle:ProductCategory:index" }
    methods:  GET

admin_productcategory_show:
    path:     /{id}/show
    defaults: { _controller: "UniAdminBundle:ProductCategory:show" }
    methods:  GET

admin_productcategory_new:
    path:     /new
    defaults: { _controller: "UniAdminBundle:ProductCategory:new" }
    methods:  [GET, POST]

admin_productcategory_edit:
    path:     /{id}/edit
    defaults: { _controller: "UniAdminBundle:ProductCategory:edit" }
    methods:  [GET, POST]

admin_productcategory_delete:
    path:     /{id}/delete
    defaults: { _controller: "UniAdminBundle:ProductCategory:delete" }
    methods:  DELETE
