admin_socialmediaenabled_index:
    path:     /
    defaults: { _controller: "UniAdminBundle:SocialMediaEnabled:index" }
    methods:  GET

admin_socialmediaenabled_show:
    path:     /{id}/show
    defaults: { _controller: "UniAdminBundle:SocialMediaEnabled:show" }
    methods:  GET

admin_socialmediaenabled_new:
    path:     /new
    defaults: { _controller: "UniAdminBundle:SocialMediaEnabled:new" }
    methods:  [GET, POST]

admin_socialmediaenabled_edit:
    path:     /{id}/edit
    defaults: { _controller: "UniAdminBundle:SocialMediaEnabled:edit" }
    methods:  [GET, POST]

admin_socialmediaenabled_delete:
    path:     /{id}/delete
    defaults: { _controller: "UniAdminBundle:SocialMediaEnabled:delete" }
    methods:  DELETE
