admin_socialmediaavailable_index:
    path:     /
    defaults: { _controller: "UniAdminBundle:SocialMediaAvailable:index" }
    methods:  GET

admin_socialmediaavailable_show:
    path:     /{id}/show
    defaults: { _controller: "UniAdminBundle:SocialMediaAvailable:show" }
    methods:  GET

admin_socialmediaavailable_new:
    path:     /new
    defaults: { _controller: "UniAdminBundle:SocialMediaAvailable:new" }
    methods:  [GET, POST]

admin_socialmediaavailable_edit:
    path:     /{id}/edit
    defaults: { _controller: "UniAdminBundle:SocialMediaAvailable:edit" }
    methods:  [GET, POST]

admin_socialmediaavailable_delete:
    path:     /{id}/delete
    defaults: { _controller: "UniAdminBundle:SocialMediaAvailable:delete" }
    methods:  DELETE
